### ISSUE TITLE
Recompiling all entry templates after changes of a non-entry partial file leads to long project rebuild

### ISSUE THREAD

**Issue by exocornet** [webdiscus/pug-plugin#66]
Hello.
Website have 30 pages and 50 components. 
Changing something in the component recompiles for a long time up to 3 minutes. Can you tell me how to incrementally build pug files and components? 
Thank you.

**Comment by webdiscus** [comment]
Hello,

could you describe what you are doing, concrete steps?
For example, one page contains Pug includes (mixins, layout, etc), styles and scripts.
- when is changed main Pug file, it take 10 sec
- when is changed included Pug file (footer), it take 20 sec
- when is changed a SCSS file, it take 3 mins
etc.

P.S. we only speak english, please use google translate

**Comment by exocornet** [comment]
I hope I understood you correctly.

Pug-plugin settings:

![entry-output](https://user-images.githubusercontent.com/57918887/224019907-5846a7b2-d553-4825-99fc-b448424afd68.png)
![list-pages](https://user-images.githubusercontent.com/57918887/224019913-e369521f-1752-439c-9714-27fd26475a95.png)
![pug-loader](https://user-images.githubusercontent.com/57918887/224019919-52fd2ca9-abe1-45c6-9555-54a54bf3ccc6.png)
![pug-plugin](https://user-images.githubusercontent.com/57918887/224019924-82ac42ac-74b9-4930-87dd-5d3859ca469c.png)

When adding a div element on the page, precompilation completed in 34439 ms.
![index](https://user-images.githubusercontent.com/57918887/224018345-e4b953e1-cd2b-404f-8e48-01a88134fa46.png)

When a low-level component changes. Used on all pages. The component is called about 60 times. Recompilation takes 255897 ms.
![component](https://user-images.githubusercontent.com/57918887/224018339-10b1338d-b063-4d7a-9376-88eb5740a104.png)

When changing the sass file, the recompilation was completed in 36273 ms.
![sass](https://user-images.githubusercontent.com/57918887/224018350-21fde4ea-249e-4974-8d98-ea7252273e01.png)

Many thanks for the help!

**Comment by webdiscus** [comment]
@exocornet 

Thanks, I will research your case.

### Note
when you change a globally used SCSS file, e.g. `base.scss`, then all pages will be rebuilt because the generated CSS filename is changed and all pages must contain the new filename in the link tag. 

### Workaround
If you have a large project, it is recommended that you define only one Pug file in the entry that you currently work on.
Just manually specify one Pug file in the entry.

**Comment by webdiscus** [comment]
@exocornet
Is the problem with using Pug in TS solved, the #62 issue? 
Possible should be used the `esModule: true` in loader option.

**Comment by webdiscus** [comment]
@exocornet 

The new pug plugin `v5.0.0` is released and based on the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin).

Try to upgrade your project to `v5`. See please the [BREAKING CHANGES](https://github.com/webdiscus/pug-plugin/blob/master/CHANGELOG.md#breaking-changes).

If the issue is still yet actual, feel free to reopen this issue.

**Comment by exocornet** [comment]
> @exocornet
> 
> The new pug plugin `v5.0.0` is released and based on the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin).
> 
> Try to upgrade your project to `v5`. See please the [BREAKING CHANGES](https://github.com/webdiscus/pug-plugin/blob/master/CHANGELOG.md#breaking-changes).
> 
> If the issue is still yet actual, feel free to reopen this issue.

Hello. I tried the new version of the plugin v5. Nothing changed. It still takes a long time to reassemble everything. :'((

**Comment by exocornet** [comment]
I’m also trying to switch to RSPack and it shows an error adding a plugin as in this answer https://github.com/webdiscus/html-bundler-webpack-plugin/issues/55#issuecomment-1852446387 .


I would be grateful if we can fix this too. I wouldn’t want to switch to old solutions and plugins since your plugin is good and I really like it. Thank you for its development and timely support.

**Comment by webdiscus** [comment]
@exocornet 

using the version `5.x` please change your Webpack config:

- remove all Pug rules in `module.rules` where is used `PugPlugin.loader`.
  The new pug plugin does not need the Pug loader config.
- new pug plugin detects all Pug pages automatically, use the [entry](https://github.com/webdiscus/html-bundler-webpack-plugin#option-entry-path) plugin option as a path to pages:
   ```js
   new PugPlugin({
     entry: 'src/pages/',
   });
   ```

P.S. This does not affect performance, but simplifies plugin config.

**Comment by webdiscus** [comment]
@exocornet 

back to the topic...

Please create a repository with a reproducible performance issue.
To simulate a problem, you can use 10 components and 5–10 pages.

I don't have a project as big as yours, so it's difficult for me to reproduce the problem. But it is very important for me to research and fix the performance issue.

**Comment by exocornet** [comment]
> @exocornet
> 
> back to the topic...
> 
> Please create a repository with a reproducible performance issue. To simulate a problem, you can use 10 components and 5–10 pages.
> 
> I don't have a project as big as yours, so it's difficult for me to reproduce the problem. But it is very important for me to research and fix the performance issue.

Of course, here's the repository - https://github.com/exocornet/pug-plugin-test . This template is my personal customization and if you are interested in something, you can take it for your personal use. But for now I would like to do a quick reload of pug during development.

**Comment by exocornet** [comment]
I'm also interested in the question. I did a little research on the "html-bundler-webpack-plugin" plugin and since pug-plugin is written in it. Is there a need for pug-plugin now? As for me, “html-bundler-webpack-plugin” gives all the same capabilities or are there still some differences between these two plugins?

**Comment by webdiscus** [comment]
>  are there still some differences between these two plugins?

No differences.

The `pug-plugin >= v5.x` is the `html-bundler-webpack-plugin` preconfigured for using pug, not more.

`pug-plugin` == `html-bundler-webpack-plugin` + `pug package` + `preprocessor: 'pug'` (preconfigured [option](https://github.com/webdiscus/html-bundler-webpack-plugin#using-template-pug) for pug)

You can read the [History of Pug Plugin](https://github.com/webdiscus/pug-plugin#history-of-pug-plugin).

- `pug-plugin` package is stay only for compatibility with projects which already uses the package
- `pug-plugin` is nice short name

**Comment by exocornet** [comment]
> But later I will add back the pug specifically `pretty` option to format minimised HTML in development mode.

![pug-pretty](https://github.com/webdiscus/pug-plugin/assets/57918887/8354d162-0ba8-48dc-a0de-0d2aa3ac0baf)

If we talk about pretty in pug, then this setting was most suitable. But she doesn’t do everything as it should :(. I haven’t found the ideal method yet and I use the one on the screenshot.

Here are examples of defective pretty html.
![1](https://github.com/webdiscus/pug-plugin/assets/57918887/099f4a0a-1259-4429-ae68-efb5b0470531)
![2](https://github.com/webdiscus/pug-plugin/assets/57918887/0f8d67b6-3fbf-4cf4-a981-c628ffbfee59)

**Comment by webdiscus** [comment]
@exocornet 

I looked your test project...
The webpack config is too heavy.

The complete project was compiled in 188000ms (over 3 minutes).
I have created a simplest `hello world` pug template with 3 lines, w/o assets and the compilation took `3.5 seconds` on my macBook M1 Pro 64 GB. It's not OK, it's realy overhead.

Firstly, I try to optimise your config.

**Comment by exocornet** [comment]
Yes, first strat (cold start). The fact that it compiles this way I think is normal. Because you need to collect everything first and then send it for withdrawal. But subsequent reassemblies, when they take the same time as the start, are sad and very strange.

 And I’m trying to improve this point and somehow raised the question and thought that maybe if your plugin is made for the configuration with an implementation for the request, then maybe this will improve the situation at least a little.  (https://github.com/webdiscus/pug-plugin/issues/93)

And speed is one of the reasons why I decided to try running my assembly via express + webpack + pug-plugin and am also already planning to switch to RSPack. But so far I don’t understand how to connect it all and make it work.

Since your plugin is not implemented for on-demand rendering (https://github.com/webdiscus/pug-plugin/issues/93), and there is still an error in RSPack.

For now, I'm making do with the temporary solution 'npm run watch', where you can enter one or more project pages. But this solution also causes a lot of inconvenience.

**Comment by webdiscus** [comment]
@exocornet 

I can reproduce the problem with needless recompilation.

For example, there are project files:

```
pages/home/index.pug <= entrypoint
pages/home/includes/header.pug (included in entrypoint)

pages/about/index.pug <= entrypoint
pages/about/includes/header.pug (included in entrypoint)
```

After changes in `pages/home/index.pug`, will be rendered only this file. `OK`
After changes in `pages/home/includes/header.pug`, will be rendered all pages:
  - pages/home/index.pug (with all dependencies) `OK`
  - pages/about/index.pug (with all dependencies) `NOT OK`, this must not be rendered

When any file included in the entrypoint file changes, webpack calls the loader for all pages. This is a BUG!

I don't know why webpack does this. I'm trying to look deeper into the problem.
This is very very hard to fix it, I can't promise that it will be fixed. The problem is deep in the webpack.

**Comment by exocornet** [comment]
Yes. I understand what you're saying. And here it is possible that the problem is not only in webpack, but also in pug itself. While studying this problem with the pug template engine, I learned that it was created as the main server-side template engine. And I tried to run it in combination with express + pug and it worked very well and quickly. But to my regret, I also need webpack. And it seems to me because of the features of pug and webpack. It would be possible to compile it through a request using the page URL. How I tried to do this in https://github.com/webdiscus/pug-plugin/issues/93
![300170760-d12463e0-1aba-44e5-b3e7-3c565a082f08](https://github.com/webdiscus/pug-plugin/assets/57918887/c7c9ce5b-0963-4aa4-863f-cf2825135bc8)

If the plugin - "pug-plugin" could exist in exactly this setting, it seems to me that with such an implementation it would be possible to speed up pug. And also use pug-plugin on the server side with express. But I could be wrong, I don’t have much experience in this and here I’m just guessing from everything I tried and tried to understand the logic of pug + webpack recompilation.

**Comment by exocornet** [comment]
> Yes. I understand what you're saying. And here it is possible that the problem is not only in webpack, but also in pug itself. While studying this problem with the pug template engine, I learned that it was created as the main server-side template engine. And I tried to run it in combination with express + pug and it worked very well and quickly. But to my regret, I also need webpack. And it seems to me because of the features of pug and webpack. It would be possible to compile it through a request using the page URL. How I tried to do this in #93 ![300170760-d12463e0-1aba-44e5-b3e7-3c565a082f08](https://private-user-images.githubusercontent.com/57918887/311524762-c7c9ce5b-0963-4aa4-863f-cf2825135bc8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODg0MDAsIm5iZiI6MTcxMDA4ODEwMCwicGF0aCI6Ii81NzkxODg4Ny8zMTE1MjQ3NjItYzdjOWNlNWItMDk2My00YWE0LTg2M2YtY2YyODI1MTM1YmM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE2MjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZTA1Y2U5ODUyOTRkOTRjNmIxNDEwMmI5ODJkN2FiZDU1NjZiMjdkY2U3M2EyOWEyYWNkNzNmNjQ5ZTcwYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4aF7wslMfugkf97QGufpHbAVnD7zZGw9QDbbKiZGujY)
> 
> If the plugin - "pug-plugin" could exist in exactly this setting, it seems to me that with such an implementation it would be possible to speed up pug. And also use pug-plugin on the server side with express. But I could be wrong, I don’t have much experience in this and here I’m just guessing from everything I tried and tried to understand the logic of pug + webpack recompilation.


But here’s how to implement the first launch and assembly via webpack, and subsequently only upon request from the page url. There may also be difficulties here, but perhaps this is not the most difficult situation, like accelerating the reassembly of pug 😄 :)

**Comment by webdiscus** [comment]
@exocornet 

By compilation single HTML file w/o any template engine will be sometime the compilation twice called.

The same issue with `html-webpack-plugin` - [Double compilation with webpack 5 and webpack-dev-server](https://github.com/jantimon/html-webpack-plugin/issues/1576).

This is really webpack bug, not pug.

**Comment by exocornet** [comment]
> @exocornet
> 
> By compilation single HTML file w/o any template engine will be sometime the compilation twice called.
> 
> The same issue with `html-webpack-plugin` - [Double compilation with webpack 5 and webpack-dev-server](https://github.com/jantimon/html-webpack-plugin/issues/1576).
> 
> This is really webpack bug, not pug.

Perhaps you are right. But what I see in this problem is not very similar to my situation. Since for me it simply reassembles all pages, as it should be on the server side without using HMR. And in the problem that you found, you simply called the same rebuild twice. It happens to me once, but that’s all. And plus, this problem is already 4 years old, it may have been fixed a long time ago.

**Comment by exocornet** [comment]
> > Yes. I understand what you're saying. And here it is possible that the problem is not only in webpack, but also in pug itself. While studying this problem with the pug template engine, I learned that it was created as the main server-side template engine. And I tried to run it in combination with express + pug and it worked very well and quickly. But to my regret, I also need webpack. And it seems to me because of the features of pug and webpack. It would be possible to compile it through a request using the page URL. How I tried to do this in #93 ![300170760-d12463e0-1aba-44e5-b3e7-3c565a082f08](https://private-user-images.githubusercontent.com/57918887/311524762-c7c9ce5b-0963-4aa4-863f-cf2825135bc8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODg0MDAsIm5iZiI6MTcxMDA4ODEwMCwicGF0aCI6Ii81NzkxODg4Ny8zMTE1MjQ3NjItYzdjOWNlNWItMDk2My00YWE0LTg2M2YtY2YyODI1MTM1YmM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE2MjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZTA1Y2U5ODUyOTRkOTRjNmIxNDEwMmI5ODJkN2FiZDU1NjZiMjdkY2U3M2EyOWEyYWNkNzNmNjQ5ZTcwYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4aF7wslMfugkf97QGufpHbAVnD7zZGw9QDbbKiZGujY)
> > If the plugin - "pug-plugin" could exist in exactly this setting, it seems to me that with such an implementation it would be possible to speed up pug. And also use pug-plugin on the server side with express. But I could be wrong, I don’t have much experience in this and here I’m just guessing from everything I tried and tried to understand the logic of pug + webpack recompilation.
> 
> But here’s how to implement the first launch and assembly via webpack, and subsequently only upon request from the page url. There may also be difficulties here, but perhaps this is not the most difficult situation, like accelerating the reassembly of pug 😄 :)

Tell me, is it possible that your plugin (pug-plugin) can be made to work like this?

**Comment by webdiscus** [comment]
>  this problem is already 4 years old, it may have been fixed a long time ago.

To this day this problem still exists. I can reproduce this reliably when compilation is called twice after change single html file.

Yes, this is a slightly different problem, but it may still be indirectly related to the current problem.

**Comment by webdiscus** [comment]
> If the plugin - "pug-plugin" could exist in exactly this setting, it seems to me that with such an implementation it would be possible to speed up pug. And also use pug-plugin on the server side with express. But I could be wrong, I don’t have much experience in this and here I’m just guessing from everything I tried and tried to understand the logic of pug + webpack recompilation.

no, the `pug-plugin` works only with webpack and cannot work with express as midleware, like on you screenshot. This is absolutely two differente worlds.

**Comment by exocornet** [comment]
Eheh, I understand. Then I will try to further fix the problem.

**Comment by webdiscus** [comment]
I'm still searching for a solution to the problem when the dependent file of one page is changed, but all pages are recompiled.

**Comment by webdiscus** [comment]
## Notes

### Twice recompilation

To fix twice recompilation the same file just add the `aggregateTimeout` option:

```js
watchOptions: {
    // fix twice recompilation the same file
    aggregateTimeout: 600,
},
```

### Compiling all entrypoint files after changes of a non-entry file.

When is changed the entrypoint template file, then will be recompiled only this entry file (with dependencies).
Wenn is changed any template partial file (file is not entrypoint), then webpack will recompile all entrypoint files, because hasn't inner dependency tree for templates and don't know which entrypoint is parent to the partial file.

This is a big problem. Currently I don't see a clever solution, sorry. Perhaps, we need develop own caching system with own dependency tree of template files (possible not for all templating engines).

**Comment by exocornet** [comment]
Although it was not possible to solve the problem, I have now found the cause. And I know what we should do. Thank you very much for your help and your interest. I think it will be possible to solve not only this problem. Thank you very much again!

**Comment by exocornet** [comment]
Can you tell me whether "pug-plugin" will support RSPack and how soon this might happen?

**Comment by webdiscus** [comment]
@exocornet 

in the version `5.0.1` following bug is fixed:
- recompiling all entry templates after changes of a non-entry partial file

## Note:

- If you change a page specifically partial e.g. `src/pages/index/styles-and-scripts/index.link.pug`, then will be recompiled only `index` page (ca. 5 sec). This case is fixed.

- If you change common used partial, e.g. a component mixin or layout, then will be recompiled all entries, it is OK

**Comment by webdiscus** [comment]
@exocornet 

does the fix work for you?
Can be closed the issue?

For other issue, please open new issue.

**Comment by exocornet** [comment]
Thank you. I will definitely update to this version.

Have you seen this plugin?
https://rsbuild.dev/plugins/list/plugin-pug

What's interesting is that it's on rsbuild. Although I am attracted by the more native component of rspack. But suddenly this solution will help solve some problems.

**Comment by webdiscus** [comment]
> https://rsbuild.dev/plugins/list/plugin-pug

It is very primitive and don't have reach functionality as my plugin ;-)
For me the plugin is unusable.

**Comment by exocornet** [comment]
> @exocornet
> 
> does the fix work for you? Can be closed the issue?
> 
> For other issue, please open new issue.

Well, the problem itself was never solved. The problem was the long reassembly of the project. When in other frameworks or template engines this all happens instantly. :( But if you have nothing else to help you with, then of course close it. I am grateful to you for such help. Thank you!

**Comment by exocornet** [comment]
> > https://rsbuild.dev/plugins/list/plugin-pug
> 
> It is very primitive and don't have reach functionality as my plugin ;-) For me the plugin is unusable.

Got it, okay. I was just thinking maybe what mechanism could be implemented so that your plugin would be even better 😊

**Comment by webdiscus** [comment]
> The problem was the long reassembly of the project. 

Your project is very big, over 40 pages, over 800 source files.
The first compilation of one page takes ~12 seconds! Recompilation takes ~4.5-5 seconds.

**Comment by exocornet** [comment]
> > The problem was the long reassembly of the project.
> 
> Your project is very big, over 40 pages, over 800 source files. The first compilation of one page takes ~12 seconds! Recompilation takes ~4.5-5 seconds.

Well, I think you've improved anyway. I will still try to find something that would work faster 😁 and HMR would be million-bearing. I think I will turn to you more than once for advice or opinion. Thank you!

**Comment by webdiscus** [comment]
> I was just thinking maybe what mechanism could be implemented so that your plugin would be even better 

No special rspack mechanism was found.
In the rsbuild pug-plugin is only "3 lines" pure JS code:
- get config
- run compilation of pug source
- output

**Comment by webdiscus** [comment]
>  I think I will turn to you more than once for advice or opinion.

Yes, sure.

Thank you for help to improve this plugin!

**Comment by webdiscus** [comment]
@exocornet 

I found why your project is builded too long.
The problem is with including the `src/sections/StatisticsMap/include-svg/world-map.pug` file.
It is very big SVG file in Pug format with paar variables.

I have saved the rendered SVG into separate svg file and added one in the `src/sections/StatisticsMap/StatisticsMap.pug` template as img tag:
```diff
- include include-svg/world-map
+ img(src='IMAGES/statisticsMap.svg' class=styles.statisticsMapWorldMap)
```

Build time for one page with SVG as Pug: `~9 seconds`, recompilation - `~5` seconds
Build time for one page with SVG as img: `~4.5 seconds`, recompilation - `~0.7` seconds only (!)

Total compilation of all pages takes `~24 seconds`.

### My recommendation

You can pre-render all variants of SVG images (with all variables) and use a variable name of the SVG file instead of rendering SVG "on fly".
